name: Build Android APK (Cordova)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Cordova
        run: npm i -g cordova

      - name: Setup Java (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install project deps
        run: npm ci || npm i

      - name: Add Android platform & build
        run: |
          npx cordova platform add android
          npx cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: portscanner-debug-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
